import { SampleLeaf } from "./types";

export const sampleLeaves: SampleLeaf[] = [
  {
    id: "sample-tomato-early-blight",
    cropName: "Tomato",
    cropNameBn: "টমেটো",
    diseaseName: "Early Blight",
    diseaseNameBn: "আর্লি ব্লাইট (আগাম ধ্বসা)",
    tag: "Tomato Leaf",
    imageUrl: "https://images.unsplash.com/photo-1592417817098-8f3d6eb228cc?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "sample-potato-late-blight",
    cropName: "Potato",
    cropNameBn: "আলু",
    diseaseName: "Late Blight",
    diseaseNameBn: "লেট ব্লাইট (নাবী ধ্বসা)",
    tag: "Potato Leaf",
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "sample-chili-leaf-curl",
    cropName: "Chili",
    cropNameBn: "মরিচ",
    diseaseName: "Leaf Spot & Curl",
    diseaseNameBn: "পাতা দাগ ও কোঁকড়ানো",
    tag: "Chili Leaf",
    imageUrl: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "sample-corn-leaf-spot",
    cropName: "Corn",
    cropNameBn: "ভুট্টা",
    diseaseName: "Cercospora Leaf Spot",
    diseaseNameBn: "সারকোস্পোরা পাতার দাগ",
    tag: "Corn Leaf",
    imageUrl: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "sample-cucumber-mildew",
    cropName: "Cucumber",
    cropNameBn: "শসা",
    diseaseName: "Powdery Mildew",
    diseaseNameBn: "পাউডারি মিলডিউ",
    tag: "Cucumber Leaf",
    imageUrl: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "sample-rice-blast",
    cropName: "Rice",
    cropNameBn: "ধান",
    diseaseName: "Rice Blast",
    diseaseNameBn: "ধানের ব্লাস্ট রোগ",
    tag: "Rice Paddy",
    imageUrl: "https://images.unsplash.com/photo-1536704689677-27b003a2760a?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "sample-brinjal-blight",
    cropName: "Brinjal",
    cropNameBn: "বেগুন",
    diseaseName: "Phomopsis Blight",
    diseaseNameBn: "ফোমোপসিস ব্লাইট",
    tag: "Brinjal Leaf",
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "sample-garlic-purple",
    cropName: "Garlic",
    cropNameBn: "রসুন",
    diseaseName: "Purple Blotch",
    diseaseNameBn: "বেগুনী দাগ রোগ",
    tag: "Garlic Leaf",
    imageUrl: "https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=600&auto=format&fit=crop&q=80",
  },
];
